//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 配置层面所有关于Blackboard key的枚举
    /// </summary>
    public enum BlackboardKey
    {
        /// <summary>
        /// 击中音效
        /// </summary>
        HitSound = 0,
        /// <summary>
        /// 击中特效
        /// </summary>
        HitFx = 1,
    }

} 
