//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 包含整个游戏内所有的控制码
    /// </summary>
    public enum ControlCode
    {
        /// <summary>
        /// 空
        /// </summary>
        None = 0,
        /// <summary>
        /// 停止
        /// </summary>
        Stop = 1,
        /// <summary>
        /// 方向移动
        /// </summary>
        MoveOfDirection = 2,
        /// <summary>
        /// 点移动
        /// </summary>
        MoveOfPoint = 3,
        /// <summary>
        /// 强势点移动
        /// </summary>
        MoveOfPoint_Force = 4,
        /// <summary>
        /// 跃进
        /// </summary>
        Leap = 5,
        /// <summary>
        /// 指向
        /// </summary>
        Direction = 6,
        /// <summary>
        /// 自动触发
        /// </summary>
        AutoTrigger = 7,
        /// <summary>
        /// 技能1
        /// </summary>
        Ability1 = 8,
        /// <summary>
        /// 技能2
        /// </summary>
        Ability2 = 9,
        /// <summary>
        /// 技能3
        /// </summary>
        Ability3 = 10,
        /// <summary>
        /// 技能4
        /// </summary>
        Ability4 = 11,
        /// <summary>
        /// 技能5
        /// </summary>
        Ability5 = 12,
        /// <summary>
        /// 技能6
        /// </summary>
        Ability6 = 13,
    }

} 
