//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    public enum DamageType
    {
        /// <summary>
        /// 物理伤害
        /// </summary>
        PhysicalDamage = 0,
        /// <summary>
        /// 光属性伤害
        /// </summary>
        LightDamage = 1,
        /// <summary>
        /// 暗属性伤害
        /// </summary>
        DarkDamage = 2,
        /// <summary>
        /// 火属性伤害
        /// </summary>
        FireDamage = 3,
        /// <summary>
        /// 冰属性伤害
        /// </summary>
        IceDamage = 4,
        /// <summary>
        /// 真实伤害
        /// </summary>
        TrueDamage = 5,
    }

} 
