//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    public enum FactionModel
    {
        /// <summary>
        /// 安全模式只有怪物是敌人
        /// </summary>
        Safe = 0,
        /// <summary>
        /// 敌对模式下, 不同阵营的其他玩家也是敌人
        /// </summary>
        Enemy = 1,
        /// <summary>
        /// 除了队友全是敌人
        /// </summary>
        All = 2,
    }

} 
