//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 本地化key类型
    /// </summary>
    public enum LocalizationKey
    {
        cd = 0,
        mana_cost = 1,
        detect_range = 2,
    }

} 
