//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 包含整个游戏内所有的关于数值方面的定义
    /// </summary>
    public enum NumericType
    {
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1,
        /// <summary>
        /// 当前血量
        /// </summary>
        Hp = 2,
        /// <summary>
        /// 最大护盾
        /// </summary>
        MaxShield = 3,
        /// <summary>
        /// 当前护盾
        /// </summary>
        Shield = 4,
        /// <summary>
        /// 最大魔法值
        /// </summary>
        MaxMana = 5,
        /// <summary>
        /// 当前魔法值
        /// </summary>
        Mana = 6,
        /// <summary>
        /// 升级经验
        /// </summary>
        MaxExp = 7,
        /// <summary>
        /// 当前经验
        /// </summary>
        Exp = 8,
        /// <summary>
        /// recover hp
        /// </summary>
        Rhp = 9,
        /// <summary>
        /// recover shield
        /// </summary>
        Rshield = 10,
        /// <summary>
        /// recover mana
        /// </summary>
        Rmana = 11,
        /// <summary>
        /// 物理攻击
        /// </summary>
        Patk = 12,
        /// <summary>
        /// 光属性攻击 light attack
        /// </summary>
        Latk = 13,
        /// <summary>
        /// 暗属性攻击 dark attack
        /// </summary>
        Datk = 14,
        /// <summary>
        /// 火属性攻击 fire attack
        /// </summary>
        Fatk = 15,
        /// <summary>
        /// 冰属性攻击 ice attack
        /// </summary>
        Iatk = 16,
        /// <summary>
        /// 物暴
        /// </summary>
        Pcirt = 17,
        /// <summary>
        /// 物暴强化physic cirt intensify
        /// </summary>
        Pcit = 18,
        /// <summary>
        /// 症状强化symptom intensify
        /// </summary>
        Sit = 19,
        /// <summary>
        /// 症状抵抗symptom resist
        /// </summary>
        Srt = 20,
        /// <summary>
        /// 护甲
        /// </summary>
        Amr = 21,
        /// <summary>
        /// light resistance
        /// </summary>
        Lrt = 22,
        /// <summary>
        /// dark resistance
        /// </summary>
        Drt = 23,
        /// <summary>
        /// fire resistance
        /// </summary>
        Frt = 24,
        /// <summary>
        /// ice resistance
        /// </summary>
        Irt = 25,
        /// <summary>
        /// 移速
        /// </summary>
        Mspd = 26,
        /// <summary>
        /// 攻速快了, 除了读条和蓄力, 其他速度都会增加
        /// </summary>
        Aspd = 27,
        /// <summary>
        /// 施法速度影响读条和蓄力的速度
        /// </summary>
        Cspd = 28,
        /// <summary>
        /// 法术极速(也就是传统的冷却缩减) ability haste(int转float)
        /// </summary>
        Ahaste = 29,
        /// <summary>
        /// 目标数 target count
        /// </summary>
        Ttc = 30,
        /// <summary>
        /// 投射物速度 throwables speed
        /// </summary>
        Tspd = 31,
        /// <summary>
        /// 投射物大小 throwables size
        /// </summary>
        Tsize = 32,
        /// <summary>
        /// 投射物数量 throwables count
        /// </summary>
        Tct = 33,
        /// <summary>
        /// 物理吸血
        /// </summary>
        Pvamp = 34,
        /// <summary>
        /// 命中
        /// </summary>
        Dex = 35,
        /// <summary>
        /// 闪避
        /// </summary>
        Eva = 36,
        /// <summary>
        /// 格挡(int转float)
        /// </summary>
        Blk = 37,
        /// <summary>
        /// 幸运(int转float)
        /// </summary>
        Lucy = 38,
        /// <summary>
        /// 攻击硬直 attack stun(int转float)
        /// </summary>
        Astun = 39,
        /// <summary>
        /// 受击硬直 hurt stun(int转float)
        /// </summary>
        Hstun = 40,
        /// <summary>
        /// 威胁值, 对敌方的威胁程度
        /// </summary>
        Threat = 41,
        /// <summary>
        /// 警惕值, 和威胁值相互作用
        /// </summary>
        Vigilant = 42,
        /// <summary>
        /// 攻击欲望attack desire(int转float)
        /// </summary>
        Ads = 43,
        /// <summary>
        /// 施法范围 cast range
        /// </summary>
        Crange = 44,
        /// <summary>
        /// 检测范围 detect range
        /// </summary>
        Drange = 45,
        /// <summary>
        /// 侦查范围 spy range
        /// </summary>
        Srange = 46,
        /// <summary>
        /// 拾取范围 pickup range
        /// </summary>
        Prange = 47,
        /// <summary>
        /// EnergyCost
        /// </summary>
        Ecost = 48,
        /// <summary>
        /// EnergyAugment
        /// </summary>
        Eaug = 49,
        /// <summary>
        /// 身高
        /// </summary>
        Height = 50,
        /// <summary>
        /// 视度 Field of view
        /// </summary>
        Fov = 51,
        /// <summary>
        /// 等级level
        /// </summary>
        LV = 52,
        /// <summary>
        /// 冷却时间 cooldown
        /// </summary>
        CD = 53,
        /// <summary>
        /// 蓝耗
        /// </summary>
        ManaCost = 54,
        /// <summary>
        /// 最大召唤数 max summoning num
        /// </summary>
        Msn = 55,
        /// <summary>
        /// 叠加层数
        /// </summary>
        Stack = 56,
        /// <summary>
        /// 最大叠加层数
        /// </summary>
        MaxStack = 57,
        /// <summary>
        /// 施法时要求目标的角度在范围内
        /// </summary>
        CastAngle = 58,
    }

} 
