//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 包含整个游戏内所有的标签
    /// </summary>
    public enum TagType
    {
        /// <summary>
        /// 个体
        /// </summary>
        Unit = 0,
        /// <summary>
        /// 身份tag
        /// </summary>
        Hero = 1,
        NPC = 2,
        /// <summary>
        /// 怪物
        /// </summary>
        Monster = 3,
        /// <summary>
        /// 技能tag
        /// </summary>
        Ability = 4,
        /// <summary>
        /// 待机技能
        /// </summary>
        AbilityIdle = 5,
        /// <summary>
        /// 停止技能
        /// </summary>
        AbilityStop = 6,
        /// <summary>
        /// 移动类技能
        /// </summary>
        AbilityMove = 7,
        /// <summary>
        /// 点击移动技能
        /// </summary>
        AbilityMoveOfPoint = 8,
        /// <summary>
        /// 方向移动技能
        /// </summary>
        AbilityMoveOfDirection = 9,
        /// <summary>
        /// 攻击类技能
        /// </summary>
        AbilityAttack = 10,
        /// <summary>
        /// 普攻类技能
        /// </summary>
        AbilityNormalAttack = 11,
        /// <summary>
        /// 隐式类技能
        /// </summary>
        AbilityImplicit = 12,
        /// <summary>
        /// 显式类技能
        /// </summary>
        AbilityExplicit = 13,
        /// <summary>
        /// 显示信息类技能
        /// </summary>
        AbilityShowMessage = 14,
        /// <summary>
        /// 召唤类技能
        /// </summary>
        AbilitySummoning = 15,
        /// <summary>
        /// 读条类技能
        /// </summary>
        AbilityReading = 16,
        /// <summary>
        /// 状态tag
        /// </summary>
        Status = 17,
        /// <summary>
        /// 死亡状态
        /// </summary>
        StatusDeath = 18,
        /// <summary>
        /// 复活状态
        /// </summary>
        StatusResurgence = 19,
        /// <summary>
        /// 受击硬直状态
        /// </summary>
        StatusHitStun = 20,
        /// <summary>
        /// 控制类状态
        /// </summary>
        StatusContorl = 21,
        /// <summary>
        /// 已死亡
        /// </summary>
        Dead = 22,
    }

} 
