//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.actor
{ 

public sealed partial class TbActorConfig
{
    private readonly List<actor.ActorConfig> _dataList;
    
    private Dictionary<int, actor.ActorConfig> _dataMap_id;
    private Dictionary<string, actor.ActorConfig> _dataMap_alias;

    public TbActorConfig(JSONNode _json)
    {
        _dataList = new List<actor.ActorConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = actor.ActorConfig.DeserializeActorConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, actor.ActorConfig>();
        _dataMap_alias = new Dictionary<string, actor.ActorConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<actor.ActorConfig> DataList => _dataList;

    public actor.ActorConfig GetById(int key) => _dataMap_id.TryGetValue(key, out actor.ActorConfig __v) ? __v : null;
    public actor.ActorConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out actor.ActorConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}