//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.game
{ 

public sealed partial class GameSingletonConfig :  Bright.Config.BeanBase 
{
    public GameSingletonConfig(JSONNode _json) 
    {
        { if(!_json["card_backpack_cap"].IsNumber) { throw new SerializationException(); }  CardBackpackCap = _json["card_backpack_cap"]; }
        { if(!_json["card_store_refresh_cost"].IsNumber) { throw new SerializationException(); }  CardStoreRefreshCost = _json["card_store_refresh_cost"]; }
        { if(!_json["coin_each"].IsNumber) { throw new SerializationException(); }  CoinEach = _json["coin_each"]; }
        PostInit();
    }

    public GameSingletonConfig(int card_backpack_cap, int card_store_refresh_cost, int coin_each ) 
    {
        this.CardBackpackCap = card_backpack_cap;
        this.CardStoreRefreshCost = card_store_refresh_cost;
        this.CoinEach = coin_each;
        PostInit();
    }

    public static GameSingletonConfig DeserializeGameSingletonConfig(JSONNode _json)
    {
        return new game.GameSingletonConfig(_json);
    }

    /// <summary>
    /// 卡牌背包容量
    /// </summary>
    public int CardBackpackCap { get; private set; }
    /// <summary>
    /// 卡牌商店刷新消耗金币
    /// </summary>
    public int CardStoreRefreshCost { get; private set; }
    /// <summary>
    /// 每次购物恢复的金币数
    /// </summary>
    public int CoinEach { get; private set; }

    public const int __ID__ = 901671103;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "CardBackpackCap:" + CardBackpackCap + ","
        + "CardStoreRefreshCost:" + CardStoreRefreshCost + ","
        + "CoinEach:" + CoinEach + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
