//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 阵营类型, 敌方阵营, 友方阵营
    /// </summary>
    [System.Flags]
    public enum FactionType
    {
        /// <summary>
        /// 敌方
        /// </summary>
        Enemy = 1,
        /// <summary>
        /// 友方
        /// </summary>
        Friend = 2,
        /// <summary>
        /// 中立方
        /// </summary>
        Neutral = 4,
    }

} 
