//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    public enum NumericLayer
    {
        /// <summary>
        /// 基础层
        /// </summary>
        Bas = 1,
        /// <summary>
        /// 中间层
        /// </summary>
        Mid = 2,
        /// <summary>
        /// 终层
        /// </summary>
        Final = 3,
        Max = 4,
    }

} 
