//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 包含整个游戏内所有的关于数值方面的定义目前有几个特殊的数值, 是用int去计算float比例的, 1、法术极速2、格挡3、硬直相关4、幸运5、攻击欲望
    /// </summary>
    public enum NumericType
    {
        /// <summary>
        /// 最大血量
        /// </summary>
        MaxHp = 1,
        /// <summary>
        /// 当前血量
        /// </summary>
        Hp = 2,
        /// <summary>
        /// 最大护盾
        /// </summary>
        MaxShield = 3,
        /// <summary>
        /// 当前护盾
        /// </summary>
        Shield = 4,
        /// <summary>
        /// 最大魔法值
        /// </summary>
        MaxMana = 5,
        /// <summary>
        /// 当前魔法值
        /// </summary>
        Mana = 6,
        /// <summary>
        /// 升级经验
        /// </summary>
        MaxExp = 7,
        /// <summary>
        /// 当前经验
        /// </summary>
        Exp = 8,
        /// <summary>
        /// recover hp
        /// </summary>
        Rhp = 9,
        /// <summary>
        /// recover shield
        /// </summary>
        Rshield = 10,
        /// <summary>
        /// recover mana
        /// </summary>
        Rmana = 11,
        /// <summary>
        /// 物理攻击
        /// </summary>
        Patk = 12,
        /// <summary>
        /// 光属性攻击 light attack
        /// </summary>
        Latk = 13,
        /// <summary>
        /// 暗属性攻击 dark attack
        /// </summary>
        Datk = 14,
        /// <summary>
        /// 火属性攻击 fire attack
        /// </summary>
        Fatk = 15,
        /// <summary>
        /// 冰属性攻击 ice attack
        /// </summary>
        Iatk = 16,
        /// <summary>
        /// 物暴
        /// </summary>
        Pcirt = 17,
        /// <summary>
        /// 物暴强化physic cirt intensify
        /// </summary>
        Pcit = 18,
        /// <summary>
        /// 症状强化symptom intensify
        /// </summary>
        Sit = 19,
        /// <summary>
        /// 症状抵抗symptom resist
        /// </summary>
        Srt = 20,
        /// <summary>
        /// 护甲
        /// </summary>
        Amr = 21,
        /// <summary>
        /// light resistance
        /// </summary>
        Lrt = 22,
        /// <summary>
        /// dark resistance
        /// </summary>
        Drt = 23,
        /// <summary>
        /// fire resistance
        /// </summary>
        Frt = 24,
        /// <summary>
        /// ice resistance
        /// </summary>
        Irt = 25,
        /// <summary>
        /// 移速
        /// </summary>
        Mspd = 26,
        /// <summary>
        /// 法术极速 ability haste(int转float)
        /// </summary>
        Ahaste = 27,
        /// <summary>
        /// 目标数 target count
        /// </summary>
        Ttc = 28,
        /// <summary>
        /// 投射物速度 throwables speed
        /// </summary>
        Tspd = 29,
        /// <summary>
        /// 投射物大小 throwables size
        /// </summary>
        Tsize = 30,
        /// <summary>
        /// 投射物数量 throwables count
        /// </summary>
        Tct = 31,
        /// <summary>
        /// 物理吸血
        /// </summary>
        Pvamp = 32,
        /// <summary>
        /// 命中
        /// </summary>
        Dex = 33,
        /// <summary>
        /// 闪避
        /// </summary>
        Eva = 34,
        /// <summary>
        /// 格挡(int转float)
        /// </summary>
        Blk = 35,
        /// <summary>
        /// 幸运(int转float)
        /// </summary>
        Lucy = 36,
        /// <summary>
        /// 攻击硬直 attack stun(int转float)
        /// </summary>
        Astun = 37,
        /// <summary>
        /// 受击硬直 hurt stun(int转float)
        /// </summary>
        Hstun = 38,
        /// <summary>
        /// 攻击欲望attack desire(int转float)
        /// </summary>
        Ads = 39,
        /// <summary>
        /// 施法范围 cast range
        /// </summary>
        Crange = 40,
        /// <summary>
        /// 侦查范围 spy range
        /// </summary>
        Srange = 41,
        /// <summary>
        /// 拾取范围 pickup range
        /// </summary>
        Prange = 42,
        /// <summary>
        /// EnergyCost
        /// </summary>
        Ecost = 43,
        /// <summary>
        /// EnergyAugment
        /// </summary>
        Eaug = 44,
        /// <summary>
        /// 身高
        /// </summary>
        Height = 45,
    }

} 
