//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hsenl
{ 
    /// <summary>
    /// 阶段类型
    /// </summary>
    public enum StageType
    {
        /// <summary>
        /// 没有进入, 也可以代表阶段线结束了
        /// </summary>
        None = 0,
        /// <summary>
        /// 刚进入, 该阶段是必带的, 它代表着阶段线的开始, 在代码中默认添加
        /// </summary>
        Enter = 1,
        /// <summary>
        /// 读条
        /// </summary>
        Reading = 2,
        /// <summary>
        /// 蓄力中
        /// </summary>
        Charging = 3,
        /// <summary>
        /// 前摇
        /// </summary>
        Lifting = 4,
        /// <summary>
        /// 施法中
        /// </summary>
        Casting = 5,
        /// <summary>
        /// 后摇
        /// </summary>
        Recovering = 6,
    }

} 
