//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.cast
{ 

/// <summary>
/// 因为不能不填, 所以专门设置一个空的类型, 用来代表空
/// </summary>
public sealed partial class Null :  cast.Info 
{
    public Null(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public Null()  : base() 
    {
        PostInit();
    }

    public static Null DeserializeNull(JSONNode _json)
    {
        return new cast.Null(_json);
    }


    public const int __ID__ = 1054156534;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
