//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.adventurescheme
{ 

public abstract partial class AdventureInfo :  behavior.LeafNodeInfo 
{
    public AdventureInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public AdventureInfo(int parent_index )  : base(parent_index) 
    {
        PostInit();
    }

    public static AdventureInfo DeserializeAdventureInfo(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "DefaultCheckpointsAdventureInfo": return new adventurescheme.DefaultCheckpointsAdventureInfo(_json);
            case "DefaultBigMapAdventureInfo": return new adventurescheme.DefaultBigMapAdventureInfo(_json);
            default: throw new SerializationException();
        }
    }



    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentIndex:" + ParentIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
