//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.numeric
{ 

public sealed partial class AttachValueInfo :  numeric.Info 
{
    public AttachValueInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  Type = (NumericType)_json["type"].AsInt; }
        { if(!_json["layer"].IsNumber) { throw new SerializationException(); }  Layer = (NumericLayer)_json["layer"].AsInt; }
        { if(!_json["model"].IsNumber) { throw new SerializationException(); }  Model = (NumericModel)_json["model"].AsInt; }
        { if(!_json["value"].IsNumber) { throw new SerializationException(); }  Value = _json["value"]; }
        { if(!_json["sign"].IsString) { throw new SerializationException(); }  Sign = _json["sign"]; }
        PostInit();
    }

    public AttachValueInfo(NumericType type, NumericLayer layer, NumericModel model, double value, string sign )  : base() 
    {
        this.Type = type;
        this.Layer = layer;
        this.Model = model;
        this.Value = value;
        this.Sign = sign;
        PostInit();
    }

    public static AttachValueInfo DeserializeAttachValueInfo(JSONNode _json)
    {
        return new numeric.AttachValueInfo(_json);
    }

    /// <summary>
    /// 数值类型
    /// </summary>
    public NumericType Type { get; private set; }
    /// <summary>
    /// 数值层数(在第几层计算)
    /// </summary>
    public NumericLayer Layer { get; private set; }
    /// <summary>
    /// 数值模式(按固定值或百分比计算)
    /// </summary>
    public NumericModel Model { get; private set; }
    /// <summary>
    /// 值
    /// </summary>
    public double Value { get; private set; }
    /// <summary>
    /// 值类型标记(i-int;l-long;f-float)
    /// </summary>
    public string Sign { get; private set; }

    public const int __ID__ = 1324920825;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "Layer:" + Layer + ","
        + "Model:" + Model + ","
        + "Value:" + Value + ","
        + "Sign:" + Sign + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
