//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.pickable
{ 

/// <summary>
/// 这个拾取物里包裹的是金币
/// </summary>
public sealed partial class WrappageCoinInfo :  pickable.WrappageInfo 
{
    public WrappageCoinInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["count"].IsNumber) { throw new SerializationException(); }  Count = _json["count"]; }
        PostInit();
    }

    public WrappageCoinInfo(int count )  : base() 
    {
        this.Count = count;
        PostInit();
    }

    public static WrappageCoinInfo DeserializeWrappageCoinInfo(JSONNode _json)
    {
        return new pickable.WrappageCoinInfo(_json);
    }

    public int Count { get; private set; }

    public const int __ID__ = 1667731595;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Count:" + Count + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
