//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.behavior
{ 

public sealed partial class AINodeInfo :  behavior.CompositeNodeInfo 
{
    public AINodeInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public AINodeInfo(int index, int parent_index )  : base(index,parent_index) 
    {
        PostInit();
    }

    public static AINodeInfo DeserializeAINodeInfo(JSONNode _json)
    {
        return new behavior.AINodeInfo(_json);
    }


    public const int __ID__ = -1021534412;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Index:" + Index + ","
        + "ParentIndex:" + ParentIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
