//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ability_upgrade
{ 

public sealed partial class TbAbilityUpgradeConfig
{
    private readonly Dictionary<int, ability_upgrade.AbilityUpgradeConfig> _dataMap;
    private readonly List<ability_upgrade.AbilityUpgradeConfig> _dataList;
    
    public TbAbilityUpgradeConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<int, ability_upgrade.AbilityUpgradeConfig>();
        _dataList = new List<ability_upgrade.AbilityUpgradeConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = ability_upgrade.AbilityUpgradeConfig.DeserializeAbilityUpgradeConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, ability_upgrade.AbilityUpgradeConfig> DataMap => _dataMap;
    public List<ability_upgrade.AbilityUpgradeConfig> DataList => _dataList;

    public ability_upgrade.AbilityUpgradeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ability_upgrade.AbilityUpgradeConfig Get(int key) => _dataMap[key];
    public ability_upgrade.AbilityUpgradeConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}