//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class CureHpInfo :  timeline.TimePointInfo 
{
    public CureHpInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["cure_ratio"].IsNumber) { throw new SerializationException(); }  CureRatio = _json["cure_ratio"]; }
        { if(!_json["cure_fixed"].IsNumber) { throw new SerializationException(); }  CureFixed = _json["cure_fixed"]; }
        PostInit();
    }

    public CureHpInfo(int model, float point, float cure_ratio, int cure_fixed )  : base(model,point) 
    {
        this.CureRatio = cure_ratio;
        this.CureFixed = cure_fixed;
        PostInit();
    }

    public static CureHpInfo DeserializeCureHpInfo(JSONNode _json)
    {
        return new timeline.CureHpInfo(_json);
    }

    public float CureRatio { get; private set; }
    public int CureFixed { get; private set; }

    public const int __ID__ = 1337100360;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "CureRatio:" + CureRatio + ","
        + "CureFixed:" + CureFixed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
