//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

/// <summary>
/// 奶妈的q
/// </summary>
public sealed partial class HarmOfPointBoltInfo :  timeline.TpHarmInfo 
{
    public HarmOfPointBoltInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["model_name"].IsString) { throw new SerializationException(); }  ModelName = _json["model_name"]; }
        { if(!_json["speed"].IsNumber) { throw new SerializationException(); }  Speed = _json["speed"]; }
        PostInit();
    }

    public HarmOfPointBoltInfo(int model, float point, System.Collections.Generic.List<numeric.DamageFormulaInfo> harm_formulas, string model_name, float speed )  : base(model,point,harm_formulas) 
    {
        this.ModelName = model_name;
        this.Speed = speed;
        PostInit();
    }

    public static HarmOfPointBoltInfo DeserializeHarmOfPointBoltInfo(JSONNode _json)
    {
        return new timeline.HarmOfPointBoltInfo(_json);
    }

    public string ModelName { get; private set; }
    /// <summary>
    /// 弹道速度
    /// </summary>
    public float Speed { get; private set; }

    public const int __ID__ = 1182886171;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "HarmFormulas:" + Bright.Common.StringUtil.CollectionToString(HarmFormulas) + ","
        + "ModelName:" + ModelName + ","
        + "Speed:" + Speed + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
