//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class HarmOfDibozhanBoltInfo :  timeline.TpHarmInfo 
{
    public HarmOfDibozhanBoltInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["harm_formula"].IsObject) { throw new SerializationException(); }  HarmFormula = numeric.DamageFormulaInfo.DeserializeDamageFormulaInfo(_json["harm_formula"]);  }
        { if(!_json["num"].IsNumber) { throw new SerializationException(); }  Num = _json["num"]; }
        { if(!_json["internal_time"].IsNumber) { throw new SerializationException(); }  InternalTime = _json["internal_time"]; }
        { if(!_json["internal_distance"].IsNumber) { throw new SerializationException(); }  InternalDistance = _json["internal_distance"]; }
        { if(!_json["bolt_name"].IsString) { throw new SerializationException(); }  BoltName = _json["bolt_name"]; }
        { if(!_json["collider_name"].IsString) { throw new SerializationException(); }  ColliderName = _json["collider_name"]; }
        { if(!_json["hit_fx"].IsString) { throw new SerializationException(); }  HitFx = _json["hit_fx"]; }
        { if(!_json["hit_sound"].IsString) { throw new SerializationException(); }  HitSound = _json["hit_sound"]; }
        PostInit();
    }

    public HarmOfDibozhanBoltInfo(int model, float point, numeric.DamageFormulaInfo harm_formula, int num, float internal_time, float internal_distance, string bolt_name, string collider_name, string hit_fx, string hit_sound )  : base(model,point) 
    {
        this.HarmFormula = harm_formula;
        this.Num = num;
        this.InternalTime = internal_time;
        this.InternalDistance = internal_distance;
        this.BoltName = bolt_name;
        this.ColliderName = collider_name;
        this.HitFx = hit_fx;
        this.HitSound = hit_sound;
        PostInit();
    }

    public static HarmOfDibozhanBoltInfo DeserializeHarmOfDibozhanBoltInfo(JSONNode _json)
    {
        return new timeline.HarmOfDibozhanBoltInfo(_json);
    }

    /// <summary>
    /// 伤害的配方(可造成多段伤害)((list#sep=|),numeric.DamageFormulaInfo#sep=&gt;)
    /// </summary>
    public numeric.DamageFormulaInfo HarmFormula { get; private set; }
    /// <summary>
    /// 伤害次数
    /// </summary>
    public int Num { get; private set; }
    public float InternalTime { get; private set; }
    public float InternalDistance { get; private set; }
    public string BoltName { get; private set; }
    public string ColliderName { get; private set; }
    public string HitFx { get; private set; }
    public string HitSound { get; private set; }

    public const int __ID__ = -2093156632;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        HarmFormula?.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        HarmFormula?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "HarmFormula:" + HarmFormula + ","
        + "Num:" + Num + ","
        + "InternalTime:" + InternalTime + ","
        + "InternalDistance:" + InternalDistance + ","
        + "BoltName:" + BoltName + ","
        + "ColliderName:" + ColliderName + ","
        + "HitFx:" + HitFx + ","
        + "HitSound:" + HitSound + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
