//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class HarmOfDibozhanBoltInfo :  timeline.TpHarmInfo 
{
    public HarmOfDibozhanBoltInfo(JSONNode _json)  : base(_json) 
    {
        { var __json0 = _json["harm_formulas"]; if(!__json0.IsArray) { throw new SerializationException(); } HarmFormulas = new System.Collections.Generic.List<numeric.DamageFormulaInfo>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { numeric.DamageFormulaInfo __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = numeric.DamageFormulaInfo.DeserializeDamageFormulaInfo(__e0);  }  HarmFormulas.Add(__v0); }   }
        { if(!_json["internal_time"].IsNumber) { throw new SerializationException(); }  InternalTime = _json["internal_time"]; }
        { if(!_json["internal_distance"].IsNumber) { throw new SerializationException(); }  InternalDistance = _json["internal_distance"]; }
        PostInit();
    }

    public HarmOfDibozhanBoltInfo(int model, float point, System.Collections.Generic.List<numeric.DamageFormulaInfo> harm_formulas, float internal_time, float internal_distance )  : base(model,point) 
    {
        this.HarmFormulas = harm_formulas;
        this.InternalTime = internal_time;
        this.InternalDistance = internal_distance;
        PostInit();
    }

    public static HarmOfDibozhanBoltInfo DeserializeHarmOfDibozhanBoltInfo(JSONNode _json)
    {
        return new timeline.HarmOfDibozhanBoltInfo(_json);
    }

    /// <summary>
    /// 伤害的配方(可造成多段伤害)
    /// </summary>
    public System.Collections.Generic.List<numeric.DamageFormulaInfo> HarmFormulas { get; private set; }
    public float InternalTime { get; private set; }
    public float InternalDistance { get; private set; }

    public const int __ID__ = -2093156632;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        foreach(var _e in HarmFormulas) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        foreach(var _e in HarmFormulas) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "HarmFormulas:" + Bright.Common.StringUtil.CollectionToString(HarmFormulas) + ","
        + "InternalTime:" + InternalTime + ","
        + "InternalDistance:" + InternalDistance + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
