//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class LiuXueInfo :  timeline.TsHarmInfo 
{
    public LiuXueInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["internalTime"].IsNumber) { throw new SerializationException(); }  InternalTime = _json["internalTime"]; }
        PostInit();
    }

    public LiuXueInfo(int model, float origin, float dest, System.Collections.Generic.List<numeric.DamageFormulaInfo> harm_formulas, float internalTime )  : base(model,origin,dest,harm_formulas) 
    {
        this.InternalTime = internalTime;
        PostInit();
    }

    public static LiuXueInfo DeserializeLiuXueInfo(JSONNode _json)
    {
        return new timeline.LiuXueInfo(_json);
    }

    /// <summary>
    /// 时间间隔
    /// </summary>
    public float InternalTime { get; private set; }

    public const int __ID__ = -952900597;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "HarmFormulas:" + Bright.Common.StringUtil.CollectionToString(HarmFormulas) + ","
        + "InternalTime:" + InternalTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
