//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class ModifyPriorityInfo :  timeline.TimePointInfo 
{
    public ModifyPriorityInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["resist_priority"].IsNumber) { throw new SerializationException(); }  ResistPriority = _json["resist_priority"]; }
        PostInit();
    }

    public ModifyPriorityInfo(int model, float point, int resist_priority )  : base(model,point) 
    {
        this.ResistPriority = resist_priority;
        PostInit();
    }

    public static ModifyPriorityInfo DeserializeModifyPriorityInfo(JSONNode _json)
    {
        return new timeline.ModifyPriorityInfo(_json);
    }

    /// <summary>
    /// 阻挡优先级, -1代表还原为初始值
    /// </summary>
    public int ResistPriority { get; private set; }

    public const int __ID__ = 1768607033;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "ResistPriority:" + ResistPriority + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
