//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class ModifyTagsInfo :  timeline.TimeSegmentInfo 
{
    public ModifyTagsInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["tag"].IsNumber) { throw new SerializationException(); }  Tag = (TagType)_json["tag"].AsInt; }
        PostInit();
    }

    public ModifyTagsInfo(int model, float origin, float dest, TagType tag )  : base(model,origin,dest) 
    {
        this.Tag = tag;
        PostInit();
    }

    public static ModifyTagsInfo DeserializeModifyTagsInfo(JSONNode _json)
    {
        return new timeline.ModifyTagsInfo(_json);
    }

    /// <summary>
    /// 开始时添加这个标签, 离开时再去掉
    /// </summary>
    public TagType Tag { get; private set; }

    public const int __ID__ = 1789378734;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "Tag:" + Tag + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
