//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class ResurgenceInfo :  timeline.TimePointInfo 
{
    public ResurgenceInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public ResurgenceInfo(int model, float point )  : base(model,point) 
    {
        PostInit();
    }

    public static ResurgenceInfo DeserializeResurgenceInfo(JSONNode _json)
    {
        return new timeline.ResurgenceInfo(_json);
    }


    public const int __ID__ = -2052238768;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
