//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.card
{ 

public sealed partial class TbCardConfig
{
    private readonly List<card.CardConfig> _dataList;
    
    private Dictionary<int, card.CardConfig> _dataMap_id;
    private Dictionary<string, card.CardConfig> _dataMap_alias;

    public TbCardConfig(JSONNode _json)
    {
        _dataList = new List<card.CardConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = card.CardConfig.DeserializeCardConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, card.CardConfig>();
        _dataMap_alias = new Dictionary<string, card.CardConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<card.CardConfig> DataList => _dataList;

    public card.CardConfig GetById(int key) => _dataMap_id.TryGetValue(key, out card.CardConfig __v) ? __v : null;
    public card.CardConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out card.CardConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}