//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.checkpoint
{ 

public sealed partial class TbCheckpointConfig
{
    private readonly List<checkpoint.CheckpointConfig> _dataList;
    
    private Dictionary<int, checkpoint.CheckpointConfig> _dataMap_id;
    private Dictionary<string, checkpoint.CheckpointConfig> _dataMap_alias;

    public TbCheckpointConfig(JSONNode _json)
    {
        _dataList = new List<checkpoint.CheckpointConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = checkpoint.CheckpointConfig.DeserializeCheckpointConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, checkpoint.CheckpointConfig>();
        _dataMap_alias = new Dictionary<string, checkpoint.CheckpointConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<checkpoint.CheckpointConfig> DataList => _dataList;

    public checkpoint.CheckpointConfig GetById(int key) => _dataMap_id.TryGetValue(key, out checkpoint.CheckpointConfig __v) ? __v : null;
    public checkpoint.CheckpointConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out checkpoint.CheckpointConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}