//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ai
{ 

public sealed partial class LoiterFollowMaster :  ai.AIInfo 
{
    public LoiterFollowMaster(JSONNode _json)  : base(_json) 
    {
        { if(!_json["loiter_range"].IsNumber) { throw new SerializationException(); }  LoiterRange = _json["loiter_range"]; }
        PostInit();
    }

    public LoiterFollowMaster(int parent_index, float loiter_range )  : base(parent_index) 
    {
        this.LoiterRange = loiter_range;
        PostInit();
    }

    public static LoiterFollowMaster DeserializeLoiterFollowMaster(JSONNode _json)
    {
        return new ai.LoiterFollowMaster(_json);
    }

    /// <summary>
    /// 游荡范围
    /// </summary>
    public float LoiterRange { get; private set; }

    public const int __ID__ = 271899604;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentIndex:" + ParentIndex + ","
        + "LoiterRange:" + LoiterRange + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
