//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.status
{ 

public sealed partial class StatusConfig :  Bright.Config.BeanBase 
{
    public StatusConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["alias"].IsString) { throw new SerializationException(); }  Alias = _json["alias"]; }
        { if(!_json["view_name"].IsString) { throw new SerializationException(); }  ViewName = _json["view_name"]; }
        { if(!_json["desc"].IsString) { throw new SerializationException(); }  Desc = _json["desc"]; }
        { if(!_json["duration"].IsNumber) { throw new SerializationException(); }  Duration = _json["duration"]; }
        { var __json0 = _json["numeric_infos"]; if(!__json0.IsArray) { throw new SerializationException(); } NumericInfos = new System.Collections.Generic.List<numeric.BasicValueInfo>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { numeric.BasicValueInfo __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = numeric.BasicValueInfo.DeserializeBasicValueInfo(__e0);  }  NumericInfos.Add(__v0); }   }
        { var __json0 = _json["numeric_nodes"]; if(!__json0.IsArray) { throw new SerializationException(); } NumericNodes = new System.Collections.Generic.List<numeric.AttachValueInfo>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { numeric.AttachValueInfo __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = numeric.AttachValueInfo.DeserializeAttachValueInfo(__e0);  }  NumericNodes.Add(__v0); }   }
        { var __json0 = _json["tags"]; if(!__json0.IsArray) { throw new SerializationException(); } Tags = new System.Collections.Generic.List<TagType>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { TagType __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = (TagType)__e0.AsInt; }  Tags.Add(__v0); }   }
        { if(!_json["priority_state"].IsObject) { throw new SerializationException(); }  PriorityState = priority.StateInfo.DeserializeStateInfo(_json["priority_state"]);  }
        { if(!_json["main"].IsObject) { throw new SerializationException(); }  Main = status.StatusActionInfo.DeserializeStatusActionInfo(_json["main"]);  }
        { var __json0 = _json["workers"]; if(!__json0.IsArray) { throw new SerializationException(); } Workers = new System.Collections.Generic.List<procedureline.WorkerInfo>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { procedureline.WorkerInfo __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = procedureline.WorkerInfo.DeserializeWorkerInfo(__e0);  }  Workers.Add(__v0); }   }
        PostInit();
    }

    public StatusConfig(int id, string alias, string view_name, string desc, float duration, System.Collections.Generic.List<numeric.BasicValueInfo> numeric_infos, System.Collections.Generic.List<numeric.AttachValueInfo> numeric_nodes, System.Collections.Generic.List<TagType> tags, priority.StateInfo priority_state, status.StatusActionInfo main, System.Collections.Generic.List<procedureline.WorkerInfo> workers ) 
    {
        this.Id = id;
        this.Alias = alias;
        this.ViewName = view_name;
        this.Desc = desc;
        this.Duration = duration;
        this.NumericInfos = numeric_infos;
        this.NumericNodes = numeric_nodes;
        this.Tags = tags;
        this.PriorityState = priority_state;
        this.Main = main;
        this.Workers = workers;
        PostInit();
    }

    public static StatusConfig DeserializeStatusConfig(JSONNode _json)
    {
        return new status.StatusConfig(_json);
    }

    /// <summary>
    /// 这是ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 别名
    /// </summary>
    public string Alias { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string ViewName { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 持续时间<br/>(只是默认持续时间, 游戏中可以随时更改)
    /// </summary>
    public float Duration { get; private set; }
    /// <summary>
    /// 自己的数值
    /// </summary>
    public System.Collections.Generic.List<numeric.BasicValueInfo> NumericInfos { get; private set; }
    /// <summary>
    /// 附加到目标身上的数值
    /// </summary>
    public System.Collections.Generic.List<numeric.AttachValueInfo> NumericNodes { get; private set; }
    /// <summary>
    /// 标签
    /// </summary>
    public System.Collections.Generic.List<TagType> Tags { get; private set; }
    public priority.StateInfo PriorityState { get; private set; }
    /// <summary>
    /// 动作
    /// </summary>
    public status.StatusActionInfo Main { get; private set; }
    public System.Collections.Generic.List<procedureline.WorkerInfo> Workers { get; private set; }

    public const int __ID__ = 177777264;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in NumericInfos) { _e?.Resolve(_tables); }
        foreach(var _e in NumericNodes) { _e?.Resolve(_tables); }
        PriorityState?.Resolve(_tables);
        Main?.Resolve(_tables);
        foreach(var _e in Workers) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in NumericInfos) { _e?.TranslateText(translator); }
        foreach(var _e in NumericNodes) { _e?.TranslateText(translator); }
        PriorityState?.TranslateText(translator);
        Main?.TranslateText(translator);
        foreach(var _e in Workers) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Alias:" + Alias + ","
        + "ViewName:" + ViewName + ","
        + "Desc:" + Desc + ","
        + "Duration:" + Duration + ","
        + "NumericInfos:" + Bright.Common.StringUtil.CollectionToString(NumericInfos) + ","
        + "NumericNodes:" + Bright.Common.StringUtil.CollectionToString(NumericNodes) + ","
        + "Tags:" + Bright.Common.StringUtil.CollectionToString(Tags) + ","
        + "PriorityState:" + PriorityState + ","
        + "Main:" + Main + ","
        + "Workers:" + Bright.Common.StringUtil.CollectionToString(Workers) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
