//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ability_assist
{ 

public sealed partial class TbAbilityAssistConfig
{
    private readonly List<ability_assist.AbilityAssistConfig> _dataList;
    
    private Dictionary<int, ability_assist.AbilityAssistConfig> _dataMap_id;
    private Dictionary<string, ability_assist.AbilityAssistConfig> _dataMap_alias;

    public TbAbilityAssistConfig(JSONNode _json)
    {
        _dataList = new List<ability_assist.AbilityAssistConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = ability_assist.AbilityAssistConfig.DeserializeAbilityAssistConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, ability_assist.AbilityAssistConfig>();
        _dataMap_alias = new Dictionary<string, ability_assist.AbilityAssistConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<ability_assist.AbilityAssistConfig> DataList => _dataList;

    public ability_assist.AbilityAssistConfig GetById(int key) => _dataMap_id.TryGetValue(key, out ability_assist.AbilityAssistConfig __v) ? __v : null;
    public ability_assist.AbilityAssistConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out ability_assist.AbilityAssistConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}