//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

/// <summary>
/// 如果当前技能的目标已经死亡, 则终止
/// </summary>
public sealed partial class DeadAbortCheckInfo :  timeline.TimeSegmentInfo 
{
    public DeadAbortCheckInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public DeadAbortCheckInfo(int model, float origin, float dest )  : base(model,origin,dest) 
    {
        PostInit();
    }

    public static DeadAbortCheckInfo DeserializeDeadAbortCheckInfo(JSONNode _json)
    {
        return new timeline.DeadAbortCheckInfo(_json);
    }


    public const int __ID__ = -762299145;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
