//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class ForceMovementInfo :  timeline.TimeSegmentInfo 
{
    public ForceMovementInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["distance"].IsNumber) { throw new SerializationException(); }  Distance = _json["distance"]; }
        PostInit();
    }

    public ForceMovementInfo(int model, float origin, float dest, float distance )  : base(model,origin,dest) 
    {
        this.Distance = distance;
        PostInit();
    }

    public static ForceMovementInfo DeserializeForceMovementInfo(JSONNode _json)
    {
        return new timeline.ForceMovementInfo(_json);
    }

    /// <summary>
    /// 位移距离
    /// </summary>
    public float Distance { get; private set; }

    public const int __ID__ = -1327151109;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "Distance:" + Distance + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
