//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

/// <summary>
/// 剑魔的q
/// </summary>
public sealed partial class HarmOfBoxColliderInfo :  timeline.TsHarmInfo 
{
    public HarmOfBoxColliderInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["harm_formula"].IsObject) { throw new SerializationException(); }  HarmFormula = numeric.DamageFormulaInfo.DeserializeDamageFormulaInfo(_json["harm_formula"]);  }
        { if(!_json["center"].IsObject) { throw new SerializationException(); }  Center = hmath.Vector3.DeserializeVector3(_json["center"]);  }
        { if(!_json["size"].IsObject) { throw new SerializationException(); }  Size = hmath.Vector3.DeserializeVector3(_json["size"]);  }
        PostInit();
    }

    public HarmOfBoxColliderInfo(int model, float origin, float dest, numeric.DamageFormulaInfo harm_formula, hmath.Vector3 center, hmath.Vector3 size )  : base(model,origin,dest) 
    {
        this.HarmFormula = harm_formula;
        this.Center = center;
        this.Size = size;
        PostInit();
    }

    public static HarmOfBoxColliderInfo DeserializeHarmOfBoxColliderInfo(JSONNode _json)
    {
        return new timeline.HarmOfBoxColliderInfo(_json);
    }

    public numeric.DamageFormulaInfo HarmFormula { get; private set; }
    public hmath.Vector3 Center { get; private set; }
    public hmath.Vector3 Size { get; private set; }

    public const int __ID__ = -1990865739;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        HarmFormula?.Resolve(_tables);
        Center?.Resolve(_tables);
        Size?.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        HarmFormula?.TranslateText(translator);
        Center?.TranslateText(translator);
        Size?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "HarmFormula:" + HarmFormula + ","
        + "Center:" + Center + ","
        + "Size:" + Size + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
