//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class LockAnimaInfo :  timeline.TimePointInfo 
{
    public LockAnimaInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public LockAnimaInfo(int model, float point )  : base(model,point) 
    {
        PostInit();
    }

    public static LockAnimaInfo DeserializeLockAnimaInfo(JSONNode _json)
    {
        return new timeline.LockAnimaInfo(_json);
    }


    public const int __ID__ = 1793054022;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
