//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class MoveInfo :  timeline.TimeSegmentInfo 
{
    public MoveInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["move_model"].IsNumber) { throw new SerializationException(); }  MoveModel = _json["move_model"]; }
        PostInit();
    }

    public MoveInfo(int model, float origin, float dest, int move_model )  : base(model,origin,dest) 
    {
        this.MoveModel = move_model;
        PostInit();
    }

    public static MoveInfo DeserializeMoveInfo(JSONNode _json)
    {
        return new timeline.MoveInfo(_json);
    }

    /// <summary>
    /// 移动方式, 0方向移动, 1按点移动
    /// </summary>
    public int MoveModel { get; private set; }

    public const int __ID__ = 889421644;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "MoveModel:" + MoveModel + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
