//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class OpenWarningBoardInfo :  timeline.TimePointInfo 
{
    public OpenWarningBoardInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["asset_name"].IsString) { throw new SerializationException(); }  AssetName = _json["asset_name"]; }
        { if(!_json["type"].IsNumber) { throw new SerializationException(); }  Type = _json["type"]; }
        PostInit();
    }

    public OpenWarningBoardInfo(int model, float point, string asset_name, int type )  : base(model,point) 
    {
        this.AssetName = asset_name;
        this.Type = type;
        PostInit();
    }

    public static OpenWarningBoardInfo DeserializeOpenWarningBoardInfo(JSONNode _json)
    {
        return new timeline.OpenWarningBoardInfo(_json);
    }

    /// <summary>
    /// 资源名
    /// </summary>
    public string AssetName { get; private set; }
    /// <summary>
    /// 警示标类型, 0代表剑魔q那种范围碰撞类型, 1代表ez的q那种弹道类型
    /// </summary>
    public int Type { get; private set; }

    public const int __ID__ = -303031665;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "AssetName:" + AssetName + ","
        + "Type:" + Type + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
