//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class PlayFxInfo :  timeline.TimePointInfo 
{
    public PlayFxInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["fx_name"].IsString) { throw new SerializationException(); }  FxName = _json["fx_name"]; }
        PostInit();
    }

    public PlayFxInfo(int model, float point, string fx_name )  : base(model,point) 
    {
        this.FxName = fx_name;
        PostInit();
    }

    public static PlayFxInfo DeserializePlayFxInfo(JSONNode _json)
    {
        return new timeline.PlayFxInfo(_json);
    }

    /// <summary>
    /// 特效名
    /// </summary>
    public string FxName { get; private set; }

    public const int __ID__ = -1173024543;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "FxName:" + FxName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
