//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class PlaySoundInfo :  timeline.TimePointInfo 
{
    public PlaySoundInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["clip_name"].IsString) { throw new SerializationException(); }  ClipName = _json["clip_name"]; }
        PostInit();
    }

    public PlaySoundInfo(int model, float point, string clip_name )  : base(model,point) 
    {
        this.ClipName = clip_name;
        PostInit();
    }

    public static PlaySoundInfo DeserializePlaySoundInfo(JSONNode _json)
    {
        return new timeline.PlaySoundInfo(_json);
    }

    /// <summary>
    /// 音效名
    /// </summary>
    public string ClipName { get; private set; }

    public const int __ID__ = -1855149444;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "ClipName:" + ClipName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
