//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class PlayAnimInfo :  timeline.TimePointInfo 
{
    public PlayAnimInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["anim"].IsString) { throw new SerializationException(); }  Anim = _json["anim"]; }
        PostInit();
    }

    public PlayAnimInfo(int model, float point, string anim )  : base(model,point) 
    {
        this.Anim = anim;
        PostInit();
    }

    public static PlayAnimInfo DeserializePlayAnimInfo(JSONNode _json)
    {
        return new timeline.PlayAnimInfo(_json);
    }

    public string Anim { get; private set; }

    public const int __ID__ = -1490025888;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "Anim:" + Anim + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
