//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class RemoveStatusFromTargetInfo :  timeline.TimePointInfo 
{
    public RemoveStatusFromTargetInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["status_alias"].IsString) { throw new SerializationException(); }  StatusAlias = _json["status_alias"]; }
        PostInit();
    }

    public RemoveStatusFromTargetInfo(int model, float point, string status_alias )  : base(model,point) 
    {
        this.StatusAlias = status_alias;
        PostInit();
    }

    public static RemoveStatusFromTargetInfo DeserializeRemoveStatusFromTargetInfo(JSONNode _json)
    {
        return new timeline.RemoveStatusFromTargetInfo(_json);
    }

    public string StatusAlias { get; private set; }

    public const int __ID__ = 1706277452;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Point:" + Point + ","
        + "StatusAlias:" + StatusAlias + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
