//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class TsStatusContinuousHarmInfo :  timeline.TsStatusHarmInfo 
{
    public TsStatusContinuousHarmInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["harm_formula"].IsObject) { throw new SerializationException(); }  HarmFormula = numeric.DamageFormulaInfo.DeserializeDamageFormulaInfo(_json["harm_formula"]);  }
        { if(!_json["internalTime"].IsNumber) { throw new SerializationException(); }  InternalTime = _json["internalTime"]; }
        PostInit();
    }

    public TsStatusContinuousHarmInfo(int model, float origin, float dest, numeric.DamageFormulaInfo harm_formula, float internalTime )  : base(model,origin,dest) 
    {
        this.HarmFormula = harm_formula;
        this.InternalTime = internalTime;
        PostInit();
    }

    public static TsStatusContinuousHarmInfo DeserializeTsStatusContinuousHarmInfo(JSONNode _json)
    {
        return new timeline.TsStatusContinuousHarmInfo(_json);
    }

    /// <summary>
    /// 伤害的配方
    /// </summary>
    public numeric.DamageFormulaInfo HarmFormula { get; private set; }
    /// <summary>
    /// 时间间隔
    /// </summary>
    public float InternalTime { get; private set; }

    public const int __ID__ = -233342193;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        HarmFormula?.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
        HarmFormula?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "HarmFormula:" + HarmFormula + ","
        + "InternalTime:" + InternalTime + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
