//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.timeline
{ 

public sealed partial class WenyichuanboInfo :  timeline.TsStatusHarmInfo 
{
    public WenyichuanboInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["internalTime"].IsNumber) { throw new SerializationException(); }  InternalTime = _json["internalTime"]; }
        { if(!_json["chuanbocengshu"].IsNumber) { throw new SerializationException(); }  Chuanbocengshu = _json["chuanbocengshu"]; }
        { if(!_json["chuanbofanwei"].IsNumber) { throw new SerializationException(); }  Chuanbofanwei = _json["chuanbofanwei"]; }
        PostInit();
    }

    public WenyichuanboInfo(int model, float origin, float dest, float internalTime, int chuanbocengshu, float chuanbofanwei )  : base(model,origin,dest) 
    {
        this.InternalTime = internalTime;
        this.Chuanbocengshu = chuanbocengshu;
        this.Chuanbofanwei = chuanbofanwei;
        PostInit();
    }

    public static WenyichuanboInfo DeserializeWenyichuanboInfo(JSONNode _json)
    {
        return new timeline.WenyichuanboInfo(_json);
    }

    /// <summary>
    /// 时间间隔
    /// </summary>
    public float InternalTime { get; private set; }
    /// <summary>
    /// 每次传播的层数
    /// </summary>
    public int Chuanbocengshu { get; private set; }
    /// <summary>
    /// 传播范围
    /// </summary>
    public float Chuanbofanwei { get; private set; }

    public const int __ID__ = 287052661;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Model:" + Model + ","
        + "Origin:" + Origin + ","
        + "Dest:" + Dest + ","
        + "InternalTime:" + InternalTime + ","
        + "Chuanbocengshu:" + Chuanbocengshu + ","
        + "Chuanbofanwei:" + Chuanbofanwei + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
