//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.procedureline
{ 

/// <summary>
/// 比如血量低于30%时触发xxx技能
/// </summary>
public sealed partial class HealthRatioCastInfo :  procedureline.CastWorkerInfo 
{
    public HealthRatioCastInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["ratio"].IsNumber) { throw new SerializationException(); }  Ratio = _json["ratio"]; }
        PostInit();
    }

    public HealthRatioCastInfo(float ratio )  : base() 
    {
        this.Ratio = ratio;
        PostInit();
    }

    public static HealthRatioCastInfo DeserializeHealthRatioCastInfo(JSONNode _json)
    {
        return new procedureline.HealthRatioCastInfo(_json);
    }

    /// <summary>
    /// 血量比例, 0-1之间
    /// </summary>
    public float Ratio { get; private set; }

    public const int __ID__ = -1743884939;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Ratio:" + Ratio + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
