//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.procedureline
{ 

/// <summary>
/// 添加一个默认的状态
/// </summary>
public sealed partial class ProbAdditionalStatusOnHarmInfo :  procedureline.WorkerInfo 
{
    public ProbAdditionalStatusOnHarmInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["status_alias"].IsString) { throw new SerializationException(); }  StatusAlias = _json["status_alias"]; }
        { if(!_json["probabilistic"].IsNumber) { throw new SerializationException(); }  Probabilistic = _json["probabilistic"]; }
        PostInit();
    }

    public ProbAdditionalStatusOnHarmInfo(string status_alias, float probabilistic )  : base() 
    {
        this.StatusAlias = status_alias;
        this.Probabilistic = probabilistic;
        PostInit();
    }

    public static ProbAdditionalStatusOnHarmInfo DeserializeProbAdditionalStatusOnHarmInfo(JSONNode _json)
    {
        return new procedureline.ProbAdditionalStatusOnHarmInfo(_json);
    }

    public string StatusAlias { get; private set; }
    public float Probabilistic { get; private set; }

    public const int __ID__ = 1682027382;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "StatusAlias:" + StatusAlias + ","
        + "Probabilistic:" + Probabilistic + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
