//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ai
{ 

public sealed partial class AIConfig :  Bright.Config.BeanBase 
{
    public AIConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["alias"].IsString) { throw new SerializationException(); }  Alias = _json["alias"]; }
        { var __json0 = _json["nodes"]; if(!__json0.IsArray) { throw new SerializationException(); } Nodes = new System.Collections.Generic.List<behavior.Info>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { behavior.Info __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = behavior.Info.DeserializeInfo(__e0);  }  Nodes.Add(__v0); }   }
        PostInit();
    }

    public AIConfig(int id, string alias, System.Collections.Generic.List<behavior.Info> nodes ) 
    {
        this.Id = id;
        this.Alias = alias;
        this.Nodes = nodes;
        PostInit();
    }

    public static AIConfig DeserializeAIConfig(JSONNode _json)
    {
        return new ai.AIConfig(_json);
    }

    /// <summary>
    /// 这是ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 别名
    /// </summary>
    public string Alias { get; private set; }
    public System.Collections.Generic.List<behavior.Info> Nodes { get; private set; }

    public const int __ID__ = 797625488;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Nodes) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Nodes) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Alias:" + Alias + ","
        + "Nodes:" + Bright.Common.StringUtil.CollectionToString(Nodes) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
