//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ai
{ 

public abstract partial class AIInfo :  behavior.LeafNodeInfo 
{
    public AIInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public AIInfo(int parent_index )  : base(parent_index) 
    {
        PostInit();
    }

    public static AIInfo DeserializeAIInfo(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "PlayerAutoCasterInfo": return new ai.PlayerAutoCasterInfo(_json);
            case "PatrolInfo": return new ai.PatrolInfo(_json);
            case "IntelligentAssaultInfo": return new ai.IntelligentAssaultInfo(_json);
            default: throw new SerializationException();
        }
    }



    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentIndex:" + ParentIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
