//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ai
{ 

public sealed partial class PatrolInfo :  ai.AIInfo 
{
    public PatrolInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["patrol_range"].IsNumber) { throw new SerializationException(); }  PatrolRange = _json["patrol_range"]; }
        PostInit();
    }

    public PatrolInfo(int parent_index, float patrol_range )  : base(parent_index) 
    {
        this.PatrolRange = patrol_range;
        PostInit();
    }

    public static PatrolInfo DeserializePatrolInfo(JSONNode _json)
    {
        return new ai.PatrolInfo(_json);
    }

    public float PatrolRange { get; private set; }

    public const int __ID__ = 831077056;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentIndex:" + ParentIndex + ","
        + "PatrolRange:" + PatrolRange + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
