//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ai
{ 

public sealed partial class TbAIConfig
{
    private readonly List<ai.AIConfig> _dataList;
    
    private Dictionary<int, ai.AIConfig> _dataMap_id;
    private Dictionary<string, ai.AIConfig> _dataMap_alias;

    public TbAIConfig(JSONNode _json)
    {
        _dataList = new List<ai.AIConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = ai.AIConfig.DeserializeAIConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, ai.AIConfig>();
        _dataMap_alias = new Dictionary<string, ai.AIConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<ai.AIConfig> DataList => _dataList;

    public ai.AIConfig GetById(int key) => _dataMap_id.TryGetValue(key, out ai.AIConfig __v) ? __v : null;
    public ai.AIConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out ai.AIConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}