//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.localization
{ 

public sealed partial class TbLocalizationPropConfig
{
    private readonly Dictionary<string, localization.LocalizationPropConfig> _dataMap;
    private readonly List<localization.LocalizationPropConfig> _dataList;
    
    public TbLocalizationPropConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<string, localization.LocalizationPropConfig>();
        _dataList = new List<localization.LocalizationPropConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = localization.LocalizationPropConfig.DeserializeLocalizationPropConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Alias, _v);
        }
        PostInit();
    }

    public Dictionary<string, localization.LocalizationPropConfig> DataMap => _dataMap;
    public List<localization.LocalizationPropConfig> DataList => _dataList;

    public localization.LocalizationPropConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public localization.LocalizationPropConfig Get(string key) => _dataMap[key];
    public localization.LocalizationPropConfig this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}