//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.card
{ 

public sealed partial class CardConfig :  Bright.Config.BeanBase 
{
    public CardConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["alias"].IsString) { throw new SerializationException(); }  Alias = _json["alias"]; }
        { if(!_json["view_name"].IsString) { throw new SerializationException(); }  ViewName = _json["view_name"]; }
        { if(!_json["wrappage"].IsObject) { throw new SerializationException(); }  Wrappage = card.Info.DeserializeInfo(_json["wrappage"]);  }
        { if(!_json["price"].IsNumber) { throw new SerializationException(); }  Price = _json["price"]; }
        PostInit();
    }

    public CardConfig(int id, string alias, string view_name, card.Info wrappage, int price ) 
    {
        this.Id = id;
        this.Alias = alias;
        this.ViewName = view_name;
        this.Wrappage = wrappage;
        this.Price = price;
        PostInit();
    }

    public static CardConfig DeserializeCardConfig(JSONNode _json)
    {
        return new card.CardConfig(_json);
    }

    /// <summary>
    /// 这是ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 别名
    /// </summary>
    public string Alias { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string ViewName { get; private set; }
    public card.Info Wrappage { get; private set; }
    public int Price { get; private set; }

    public const int __ID__ = -809937872;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        Wrappage?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        Wrappage?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Alias:" + Alias + ","
        + "ViewName:" + ViewName + ","
        + "Wrappage:" + Wrappage + ","
        + "Price:" + Price + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
