//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.card
{ 

/// <summary>
/// 这个卡牌里包裹的是一个技能辅助
/// </summary>
public sealed partial class WrappageAbilityAssistInfo :  card.WrappageInfo 
{
    public WrappageAbilityAssistInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["alias"].IsString) { throw new SerializationException(); }  Alias = _json["alias"]; }
        PostInit();
    }

    public WrappageAbilityAssistInfo(string alias )  : base() 
    {
        this.Alias = alias;
        PostInit();
    }

    public static WrappageAbilityAssistInfo DeserializeWrappageAbilityAssistInfo(JSONNode _json)
    {
        return new card.WrappageAbilityAssistInfo(_json);
    }

    public string Alias { get; private set; }

    public const int __ID__ = 53692714;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Alias:" + Alias + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
