//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.adventure
{ 

public sealed partial class CandidateInfo :  adventure.Info 
{
    public CandidateInfo(JSONNode _json)  : base(_json) 
    {
        { if(!_json["checkpoint_alias"].IsString) { throw new SerializationException(); }  CheckpointAlias = _json["checkpoint_alias"]; }
        { if(!_json["weight"].IsNumber) { throw new SerializationException(); }  Weight = _json["weight"]; }
        PostInit();
    }

    public CandidateInfo(string checkpoint_alias, int weight )  : base() 
    {
        this.CheckpointAlias = checkpoint_alias;
        this.Weight = weight;
        PostInit();
    }

    public static CandidateInfo DeserializeCandidateInfo(JSONNode _json)
    {
        return new adventure.CandidateInfo(_json);
    }

    public string CheckpointAlias { get; private set; }
    public int Weight { get; private set; }

    public const int __ID__ = -1641235885;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "CheckpointAlias:" + CheckpointAlias + ","
        + "Weight:" + Weight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
