//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.adventure
{ 

public sealed partial class TbAdventureConfig
{
    private readonly List<adventure.AdventureConfig> _dataList;
    
    private Dictionary<int, adventure.AdventureConfig> _dataMap_id;
    private Dictionary<string, adventure.AdventureConfig> _dataMap_alias;

    public TbAdventureConfig(JSONNode _json)
    {
        _dataList = new List<adventure.AdventureConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = adventure.AdventureConfig.DeserializeAdventureConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, adventure.AdventureConfig>();
        _dataMap_alias = new Dictionary<string, adventure.AdventureConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<adventure.AdventureConfig> DataList => _dataList;

    public adventure.AdventureConfig GetById(int key) => _dataMap_id.TryGetValue(key, out adventure.AdventureConfig __v) ? __v : null;
    public adventure.AdventureConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out adventure.AdventureConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}