//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.bolt
{ 

public sealed partial class BoltConfig :  Bright.Config.BeanBase 
{
    public BoltConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["alias"].IsString) { throw new SerializationException(); }  Alias = _json["alias"]; }
        { if(!_json["collider_name"].IsString) { throw new SerializationException(); }  ColliderName = _json["collider_name"]; }
        { if(!_json["shape"].IsNumber) { throw new SerializationException(); }  Shape = _json["shape"]; }
        { if(!_json["size_ratio"].IsNumber) { throw new SerializationException(); }  SizeRatio = _json["size_ratio"]; }
        { if(!_json["model_name"].IsString) { throw new SerializationException(); }  ModelName = _json["model_name"]; }
        PostInit();
    }

    public BoltConfig(int id, string alias, string collider_name, int shape, float size_ratio, string model_name ) 
    {
        this.Id = id;
        this.Alias = alias;
        this.ColliderName = collider_name;
        this.Shape = shape;
        this.SizeRatio = size_ratio;
        this.ModelName = model_name;
        PostInit();
    }

    public static BoltConfig DeserializeBoltConfig(JSONNode _json)
    {
        return new bolt.BoltConfig(_json);
    }

    /// <summary>
    /// 这是ID
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 别名
    /// </summary>
    public string Alias { get; private set; }
    public string ColliderName { get; private set; }
    public int Shape { get; private set; }
    public float SizeRatio { get; private set; }
    public string ModelName { get; private set; }

    public const int __ID__ = -1164417200;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Alias:" + Alias + ","
        + "ColliderName:" + ColliderName + ","
        + "Shape:" + Shape + ","
        + "SizeRatio:" + SizeRatio + ","
        + "ModelName:" + ModelName + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
