//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.bolt
{ 

public sealed partial class TbBoltConfig
{
    private readonly List<bolt.BoltConfig> _dataList;
    
    private Dictionary<int, bolt.BoltConfig> _dataMap_id;
    private Dictionary<string, bolt.BoltConfig> _dataMap_alias;

    public TbBoltConfig(JSONNode _json)
    {
        _dataList = new List<bolt.BoltConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = bolt.BoltConfig.DeserializeBoltConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, bolt.BoltConfig>();
        _dataMap_alias = new Dictionary<string, bolt.BoltConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<bolt.BoltConfig> DataList => _dataList;

    public bolt.BoltConfig GetById(int key) => _dataMap_id.TryGetValue(key, out bolt.BoltConfig __v) ? __v : null;
    public bolt.BoltConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out bolt.BoltConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}