//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ability
{ 

public sealed partial class AbilityTraitConfig :  Bright.Config.BeanBase 
{
    public AbilityTraitConfig(JSONNode _json) 
    {
        { if(!_json["id"].IsNumber) { throw new SerializationException(); }  Id = _json["id"]; }
        { if(!_json["patch"].IsNumber) { throw new SerializationException(); }  Patch = _json["patch"]; }
        PostInit();
    }

    public AbilityTraitConfig(int id, int patch ) 
    {
        this.Id = id;
        this.Patch = patch;
        PostInit();
    }

    public static AbilityTraitConfig DeserializeAbilityTraitConfig(JSONNode _json)
    {
        return new ability.AbilityTraitConfig(_json);
    }

    /// <summary>
    /// 这是ID
    /// </summary>
    public int Id { get; private set; }
    public int Patch { get; private set; }
    public ability.AbilityPatchConfig Patch_Ref { get; private set; }

    public const int __ID__ = -1183926582;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        this.Patch_Ref = (_tables["ability.TbAbilityPatchConfig"] as ability.TbAbilityPatchConfig).GetOrDefault(Patch);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Patch:" + Patch + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
