//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ability
{ 

public sealed partial class TbAbilityPatchConfig
{
    private readonly Dictionary<int, ability.AbilityPatchConfig> _dataMap;
    private readonly List<ability.AbilityPatchConfig> _dataList;
    
    public TbAbilityPatchConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<int, ability.AbilityPatchConfig>();
        _dataList = new List<ability.AbilityPatchConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = ability.AbilityPatchConfig.DeserializeAbilityPatchConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, ability.AbilityPatchConfig> DataMap => _dataMap;
    public List<ability.AbilityPatchConfig> DataList => _dataList;

    public ability.AbilityPatchConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ability.AbilityPatchConfig Get(int key) => _dataMap[key];
    public ability.AbilityPatchConfig this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}