//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.ability
{ 

public sealed partial class TbAbilityTraitConfig
{
    private readonly List<ability.AbilityTraitConfig> _dataList;
    
    private Dictionary<int, ability.AbilityTraitConfig> _dataMap_id;
    private Dictionary<string, ability.AbilityTraitConfig> _dataMap_alias;

    public TbAbilityTraitConfig(JSONNode _json)
    {
        _dataList = new List<ability.AbilityTraitConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = ability.AbilityTraitConfig.DeserializeAbilityTraitConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, ability.AbilityTraitConfig>();
        _dataMap_alias = new Dictionary<string, ability.AbilityTraitConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<ability.AbilityTraitConfig> DataList => _dataList;

    public ability.AbilityTraitConfig GetById(int key) => _dataMap_id.TryGetValue(key, out ability.AbilityTraitConfig __v) ? __v : null;
    public ability.AbilityTraitConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out ability.AbilityTraitConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}