//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.common
{ 

public sealed partial class PriorityStateConfig :  Bright.Config.BeanBase 
{
    public PriorityStateConfig(JSONNode _json) 
    {
        { if(!_json["alias"].IsString) { throw new SerializationException(); }  Alias = _json["alias"]; }
        { if(!_json["priority_state"].IsObject) { throw new SerializationException(); }  PriorityState = priority.StateInfo.DeserializeStateInfo(_json["priority_state"]);  }
        PostInit();
    }

    public PriorityStateConfig(string alias, priority.StateInfo priority_state ) 
    {
        this.Alias = alias;
        this.PriorityState = priority_state;
        PostInit();
    }

    public static PriorityStateConfig DeserializePriorityStateConfig(JSONNode _json)
    {
        return new common.PriorityStateConfig(_json);
    }

    /// <summary>
    /// 别名
    /// </summary>
    public string Alias { get; private set; }
    public priority.StateInfo PriorityState { get; private set; }

    public const int __ID__ = -410020276;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PriorityState?.Resolve(_tables);
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        PriorityState?.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "Alias:" + Alias + ","
        + "PriorityState:" + PriorityState + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
