//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.casterevaluate
{ 

public abstract partial class CasterEvaluateInfo :  behavior.LeafNodeInfo 
{
    public CasterEvaluateInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public CasterEvaluateInfo(int parent_index )  : base(parent_index) 
    {
        PostInit();
    }

    public static CasterEvaluateInfo DeserializeCasterEvaluateInfo(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "CooldownCheckInfo": return new casterevaluate.CooldownCheckInfo(_json);
            case "ManaCheckInfo": return new casterevaluate.ManaCheckInfo(_json);
            case "PrioritiesEvaluateInfo": return new casterevaluate.PrioritiesEvaluateInfo(_json);
            case "TargetEvaluateInfo": return new casterevaluate.TargetEvaluateInfo(_json);
            case "PickTargetInfo": return new casterevaluate.PickTargetInfo(_json);
            case "PickBackTarget": return new casterevaluate.PickBackTarget(_json);
            case "ApproachTargetInfo": return new casterevaluate.ApproachTargetInfo(_json);
            case "HealthLowerInfo": return new casterevaluate.HealthLowerInfo(_json);
            case "CasterSummoningInfo": return new casterevaluate.CasterSummoningInfo(_json);
            default: throw new SerializationException();
        }
    }



    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentIndex:" + ParentIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
