//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.casterevaluate
{ 

/// <summary>
/// 评估目标是否符合条件, 但不主动挑选目标
/// </summary>
public sealed partial class TargetEvaluateInfo :  casterevaluate.CasterEvaluateInfo 
{
    public TargetEvaluateInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public TargetEvaluateInfo(int parent_index )  : base(parent_index) 
    {
        PostInit();
    }

    public static TargetEvaluateInfo DeserializeTargetEvaluateInfo(JSONNode _json)
    {
        return new casterevaluate.TargetEvaluateInfo(_json);
    }


    public const int __ID__ = 1232786689;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "ParentIndex:" + ParentIndex + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
