//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.faction
{ 

public sealed partial class TbFactionConfig
{
    private readonly Dictionary<TagType, faction.FactionConfig> _dataMap;
    private readonly List<faction.FactionConfig> _dataList;
    
    public TbFactionConfig(JSONNode _json)
    {
        _dataMap = new Dictionary<TagType, faction.FactionConfig>();
        _dataList = new List<faction.FactionConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = faction.FactionConfig.DeserializeFactionConfig(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.FactionTag, _v);
        }
        PostInit();
    }

    public Dictionary<TagType, faction.FactionConfig> DataMap => _dataMap;
    public List<faction.FactionConfig> DataList => _dataList;

    public faction.FactionConfig GetOrDefault(TagType key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public faction.FactionConfig Get(TagType key) => _dataMap[key];
    public faction.FactionConfig this[TagType key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}