//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.cast
{ 

/// <summary>
/// 只在条件符合时触发
/// </summary>
public abstract partial class ConditionCastOfWorkerInfo :  cast.Info 
{
    public ConditionCastOfWorkerInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public ConditionCastOfWorkerInfo()  : base() 
    {
        PostInit();
    }

    public static ConditionCastOfWorkerInfo DeserializeConditionCastOfWorkerInfo(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "HarmProbabilisticCastInfo": return new cast.HarmProbabilisticCastInfo(_json);
            case "HealthRatioCastInfo": return new cast.HealthRatioCastInfo(_json);
            default: throw new SerializationException();
        }
    }



    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
