//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.numeric
{ 

/// <summary>
/// 数值配方
/// </summary>
public abstract partial class FormulaInfo :  numeric.Info 
{
    public FormulaInfo(JSONNode _json)  : base(_json) 
    {
        PostInit();
    }

    public FormulaInfo()  : base() 
    {
        PostInit();
    }

    public static FormulaInfo DeserializeFormulaInfo(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "FormulaInfo1": return new numeric.FormulaInfo1(_json);
            case "FormulaInfo2": return new numeric.FormulaInfo2(_json);
            case "FormulaInfo3": return new numeric.FormulaInfo3(_json);
            default: throw new SerializationException();
        }
    }



    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
