//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.numeric
{ 

/// <summary>
/// 数值信息基类
/// </summary>
public abstract partial class Info :  Bright.Config.BeanBase 
{
    public Info(JSONNode _json) 
    {
        PostInit();
    }

    public Info() 
    {
        PostInit();
    }

    public static Info DeserializeInfo(JSONNode _json)
    {
        string type = _json["$type"];
        switch (type)
        {
            case "BasicValueInfo": return new numeric.BasicValueInfo(_json);
            case "AttachValueInfo": return new numeric.AttachValueInfo(_json);
            case "FormulaInfo": return new numeric.FormulaInfo(_json);
            case "DamageFormulaInfo": return new numeric.DamageFormulaInfo(_json);
            default: throw new SerializationException();
        }
    }



    public virtual void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public virtual void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
