//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.status
{ 

public sealed partial class TbStatusConfig
{
    private readonly List<status.StatusConfig> _dataList;
    
    private Dictionary<int, status.StatusConfig> _dataMap_id;
    private Dictionary<string, status.StatusConfig> _dataMap_alias;

    public TbStatusConfig(JSONNode _json)
    {
        _dataList = new List<status.StatusConfig>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = status.StatusConfig.DeserializeStatusConfig(_row);
            _dataList.Add(_v);
        }
        _dataMap_id = new Dictionary<int, status.StatusConfig>();
        _dataMap_alias = new Dictionary<string, status.StatusConfig>();
    foreach(var _v in _dataList)
    {
        _dataMap_id.Add(_v.Id, _v);
        _dataMap_alias.Add(_v.Alias, _v);
    }
        PostInit();
    }

    public List<status.StatusConfig> DataList => _dataList;

    public status.StatusConfig GetById(int key) => _dataMap_id.TryGetValue(key, out status.StatusConfig __v) ? __v : null;
    public status.StatusConfig GetByAlias(string key) => _dataMap_alias.TryGetValue(key, out status.StatusConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }

    
    partial void PostInit();
    partial void PostResolve();
}

}