//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Hsenl.hmath
{ 

public sealed partial class Vector3 :  hmath.Info 
{
    public Vector3(JSONNode _json)  : base(_json) 
    {
        { if(!_json["x"].IsNumber) { throw new SerializationException(); }  X = _json["x"]; }
        { if(!_json["y"].IsNumber) { throw new SerializationException(); }  Y = _json["y"]; }
        { if(!_json["z"].IsNumber) { throw new SerializationException(); }  Z = _json["z"]; }
        PostInit();
    }

    public Vector3(float x, float y, float z )  : base() 
    {
        this.X = x;
        this.Y = y;
        this.Z = z;
        PostInit();
    }

    public static Vector3 DeserializeVector3(JSONNode _json)
    {
        return new hmath.Vector3(_json);
    }

    public float X { get; private set; }
    public float Y { get; private set; }
    public float Z { get; private set; }

    public const int __ID__ = -1519709518;
    public override int GetTypeId() => __ID__;

    public override void Resolve(Dictionary<string, object> _tables)
    {
        base.Resolve(_tables);
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        base.TranslateText(translator);
    }

    public override string ToString()
    {
        return "{ "
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "Z:" + Z + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}
